# Generated by Django 2.2.16 on 2020-11-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_hgjjhg'),
    ]

    operations = [
        migrations.CreateModel(
            name='JHGjhgjh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jhgjhgjhgjhg', models.BigIntegerField()),
            ],
        ),
    ]
